### ISSUE TITLE
Impossible to re-connect

### ISSUE THREAD

**Issue by RomualdYT** [imorland/flarum-ext-twofactor#19]
Hello, little bug on my side!
The 2FA is done correctly, with the generation of the backup keys.
Everything is fine. 

If I log out and enter my password in the usual way, it tells me that my password is incorrect.
I'm obliged to enter forgotten password, and change the password to log in again.
And again, if I log out and try to log in, it doesn't work with the password!

(Another detail: when I put an image inside the QRCode, it simply doesn't generate and gives me an error).
Thanks for reading and have a nice day (thanks for the extension, it's really cool!) :)

**Comment by RomualdYT** [comment]
(I'm on PHP 8.1.22)

**Comment by imorland** [comment]
Hello @RomualdYT 

What version of the extension are you using? The latest is `1.0.10`, but until `1.0.9` there was an issue with login sometimes that sounds like what you are describing here.

Firstly, please make sure you are on the latest version, and also ensure that you've cleared the Flarum cache `php flarum cache:clear`, and then hard refresh your browser. After this, everything should be fine 🤞

**Comment by RomualdYT** [comment]
Thanks for the quick reply, that must be it! :)
But I'm in 1.0.7, I can't install via compose version 1.0.10, it only tells me that no other update is available :(

**Comment by RomualdYT** [comment]
The error seemed to be mine, I managed to update, I'll try again :)

**Comment by RomualdYT** [comment]
It's working, thanks !
Sorry for the loss of time

**Comment by RomualdYT** [comment]
It's working, thanks !
Sorry for the loss of time

**Comment by imorland** [comment]
Great! No problem at all, happy to help :)
